// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkJzL5c_PiLxBQ1miVNW4cvp1b1fDO8zo',
    appId: '1:498548828224:web:0b9a5430d84e49227117a5',
    messagingSenderId: '498548828224',
    projectId: 'readspeed-app',
    authDomain: 'readspeed-app.firebaseapp.com',
    storageBucket: 'readspeed-app.firebasestorage.app',
    measurementId: 'G-LJLDRE4T1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADonqI7dYnEQAus3jskqkIBSF3baH0SxM',
    appId: '1:498548828224:android:67c18a72c0b22f4d7117a5',
    messagingSenderId: '498548828224',
    projectId: 'readspeed-app',
    storageBucket: 'readspeed-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGcyFC8N25HKvymlx68VSISSLQebHnZ5Q',
    appId: '1:498548828224:ios:9281f3d9cf340d587117a5',
    messagingSenderId: '498548828224',
    projectId: 'readspeed-app',
    storageBucket: 'readspeed-app.firebasestorage.app',
    iosClientId: '498548828224-rvb5vinqev48lrgepg59gqg9tmm7rkd6.apps.googleusercontent.com',
    iosBundleId: 'com.qossaykamel.readspeed',
  );
}
